# Generated by Django 3.0.5 on 2020-08-04 16:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Age_Freq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('frequency', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital_Records',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default='None', max_length=20)),
                ('address', models.TextField()),
                ('subd', models.CharField(default='-', max_length=20)),
                ('bed_capacity', models.IntegerField(default=0)),
                ('available', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('recovered', models.IntegerField(default=0)),
                ('fatalities', models.IntegerField(default=0)),
            ],
        ),
    ]
