# Generated by Django 3.0.5 on 2020-08-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital_records',
            name='contact',
            field=models.IntegerField(default='0123456789', max_length=10),
        ),
    ]
