# Generated by Django 3.0.5 on 2020-08-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='records',
            name='status',
            field=models.CharField(choices=[('Admitted', 'Admitted'), ('Released', 'Released'), ('Death', 'Death')], max_length=10),
        ),
    ]
