# Generated by Django 3.0.5 on 2020-08-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0003_auto_20200821_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital_records',
            name='email',
            field=models.EmailField(default='test@example.com', max_length=254),
        ),
    ]
