# Generated by Django 3.0.5 on 2020-08-14 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0004_auto_20200811_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital_records',
            old_name='fatalities',
            new_name='cfatalities',
        ),
        migrations.RenameField(
            model_name='hospital_records',
            old_name='recovered',
            new_name='crecovered',
        ),
        migrations.RenameField(
            model_name='hospital_records',
            old_name='total',
            new_name='ctotal',
        ),
        migrations.AlterField(
            model_name='hospital_records',
            name='available',
            field=models.CharField(default='0,0,0', max_length=12),
        ),
        migrations.AlterField(
            model_name='hospital_records',
            name='bed_capacity',
            field=models.CharField(default='0,0,0', max_length=12),
        ),
        migrations.AlterField(
            model_name='records',
            name='medical_history',
            field=models.CharField(max_length=50),
        ),
    ]
