# Generated by Django 3.0.5 on 2020-08-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0007_auto_20200814_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='records',
            name='status',
        ),
        migrations.AddField(
            model_name='hospital_records',
            name='blood',
            field=models.CharField(default='[0,0,0,0,0,0,0,0]', max_length=40),
        ),
        migrations.AddField(
            model_name='hospital_records',
            name='ppe',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hospital_records',
            name='ventilator',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='records',
            name='b_group',
            field=models.CharField(default='', max_length=5),
        ),
    ]
