# Generated by Django 3.0.5 on 2020-08-21 13:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0009_auto_20200819_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_Mng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.UUIDField()),
                ('date', models.DateField(default=datetime.date(2020, 8, 21))),
                ('message', models.TextField(max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Solved', 'Solved')], default='Pending', max_length=10)),
            ],
        ),
    ]
