# Generated by Django 3.0.5 on 2020-08-21 13:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0010_inventory_mng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_mng',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 21, 13, 36, 54, 650559, tzinfo=utc)),
        ),
    ]
