# Generated by Django 3.0.5 on 2020-08-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('central', '0011_auto_20200821_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_mng',
            name='date',
            field=models.DateField(),
        ),
    ]
